### ISSUE TITLE
网络处理器抛出异常，无法正常使用

### ISSUE THREAD

**Issue by 0x4c5** [project-mirai/mirai-console-wrapper#10]
```
02:39:43 [INFO] [NETWORK] Send: friendlist.GetTroopListReqV2
 02:39:44 [INFO] [NETWORK] Exception in NetworkHandler
 02:39:44 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: type mismatch 10
        at moe.him188.jcekt.internal.JceInput.readJceLongValue(JceInput.kt:209)
        at moe.him188.jcekt.internal.JceDecoder.decodeTaggedLong(JceDecoder.kt:324)
        at moe.him188.jcekt.internal.JceDecoder.decodeTaggedLong(JceDecoder.kt:23)
        at kotlinx.serialization.internal.TaggedDecoder.decodeLongElement(Tagged.kt:223)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.StGroupRankInfo$$serializer.deserialize(TroopList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.StGroupRankInfo$$serializer.deserialize(TroopList.kt:94)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:87)
        at kotlinx.serialization.internal.ListLikeSerializer.readAll(CollectionSerializers.kt:83)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:31)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetTroopListRespV2$$serializer.deserialize(TroopList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetTroopListRespV2$$serializer.deserialize(TroopList.kt:40)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at moe.him188.jcekt.Jce.load(Jce.kt:47)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:50)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:63)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize$SerializationUtils__UtilsKt(utils.kt:92)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:60)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.list.FriendList$GetTroopListSimplify.decode(FriendList.kt:83)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Him188** [comment]
请提供实用的 mirai-core 版本

**Comment by 0x4c5** [comment]
Local Console-Pure Version: 0.5.2 | Newest STABLE Console-Pure Version: 0.5.2

Local Core Version: 1.0.2 | Newest STABLE Core Version: 1.0.2
Version check complete, starting Mirai

**Comment by Him188** [comment]
在 https://mamoe/mirai 仓库已有同样 issue，故关闭这个重复的。可跟踪 https://github.com/mamoe/mirai/issues/405 获取进度
